# Generated by Django 5.0.7 on 2025-05-30 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('puerto_vallarta', 'Puerto Vallarta'), ('cancun', 'Cancún'), ('cabo_sanlucas', 'Cabo San Lucas')], max_length=50)),
                ('time_category', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], default='diurno', max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('closed_days', models.TextField(blank=True, help_text='Días de la semana en los que el negocio está cerrado, separados por comas. Ej: mon,tue,sun')),
                ('tipos_de_negocio', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_name', models.CharField(max_length=100)),
                ('owner_or_manager_whatsapp', models.CharField(max_length=20)),
                ('owner_or_manager_email', models.EmailField(max_length=254)),
                ('reservations_contact_name', models.CharField(max_length=100)),
                ('reservations_whatsapp', models.CharField(max_length=20)),
                ('reservations_email', models.EmailField(max_length=254)),
                ('current_promotions', models.CharField(blank=True, max_length=1000, null=True)),
                ('commissions', models.IntegerField(blank=True, default=0, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('stripe_id', models.CharField(blank=True, help_text='ID del producto en Stripe', max_length=255, null=True)),
                ('google_maps', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_subcategoria', models.CharField(choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable o Vegana'), ('Tiendas_locales_de_abarrotes', 'Tienda Locale de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], default='comida_rapida', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ventasapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Compañia')),
                ('giro_de_negocio', models.CharField(blank=True, choices=[('gastronomia_bebidas', [('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable o Vegana')]), ('tiendas_de_conveniencia', [('Tiendas_locales_de_abarrotes', 'Tienda Locale de Abarrotes')]), ('farmacias', [('medicamentos', 'Medicamentos y otros Productos de Farmacia')]), ('flores_y_regalos', [('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')])], max_length=1000, null=True)),
                ('tu_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de Perfil')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='ids/', verbose_name='Documento de Identidad')),
                ('role', models.CharField(choices=[('business_owner', 'Propietario de Negocio'), ('concierge', 'Concierge')], default='concierge', max_length=20, verbose_name='Rol')),
                ('city', models.CharField(choices=[('puerto_vallarta', 'Puerto Vallarta'), ('cancun', 'Cancún'), ('cabo_sanlucas', 'Cabo San Lucas')], max_length=50, verbose_name='Ciudad')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado/Sin Aprobar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
