# Generated by Django 5.0.7 on 2025-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='giro_de_negocio',
            field=models.CharField(blank=True, choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable o Vegana'), ('Tiendas_locales_de_abarrotes', 'Tienda Locale de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], max_length=150, null=True),
        ),
    ]
