# Generated by Django 5.0.7 on 2025-05-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0002_alter_userprofile_giro_de_negocio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('licencia_numero', models.CharField(max_length=20)),
                ('licencia_fecha_emision', models.DateField()),
                ('licencia_fecha_vencimiento', models.DateField()),
                ('licencia_tipo', models.CharField(max_length=50)),
                ('identificacion_oficial', models.FileField(upload_to='documentos/identificaciones/')),
                ('comprobante_domicilio', models.FileField(upload_to='documentos/comprobantes/')),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Automóvil'), ('moto', 'Motocicleta'), ('bicicleta', 'Bicicleta'), ('pie', 'A pie')], max_length=20)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_vehiculo', models.PositiveIntegerField(blank=True, null=True)),
                ('placas', models.CharField(blank=True, max_length=20, null=True)),
                ('color_vehiculo', models.CharField(blank=True, max_length=30, null=True)),
                ('tarjeta_circulacion', models.FileField(blank=True, null=True, upload_to='documentos/tarjetas_circulacion/')),
                ('seguro_vehiculo', models.FileField(blank=True, null=True, upload_to='documentos/seguros/')),
                ('cuenta_bancaria', models.CharField(max_length=30)),
                ('clabe', models.CharField(max_length=18)),
                ('banco', models.CharField(max_length=100)),
                ('titular_cuenta', models.CharField(max_length=100)),
                ('zonas_operacion', models.TextField()),
                ('dias_disponibles', models.CharField(max_length=100)),
                ('horarios_disponibles', models.CharField(max_length=100)),
                ('antecedentes_penales', models.FileField(blank=True, null=True, upload_to='documentos/antecedentes/')),
                ('foto_selfie', models.ImageField(upload_to='documentos/fotos/')),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='documentos/firmas/')),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
