# Generated by Django 5.0.7 on 2025-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0003_conductoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductoruser',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Propietario de Negocio'), ('conductor', 'Conductor')], default='concierge', max_length=20, verbose_name='Rol'),
        ),
    ]
