# Generated by Django 5.0.7 on 2025-05-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0004_conductoruser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductoruser',
            name='verificado',
        ),
        migrations.AddField(
            model_name='conductoruser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='fecha_nacimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='licencia_fecha_emision',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='licencia_fecha_vencimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='zonas_operacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Propietario de Negocio'), ('conductor', 'Conductor')], default='conductor', max_length=20, verbose_name='Rol'),
        ),
    ]
