# Generated by Django 5.0.7 on 2025-07-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0005_remove_conductoruser_verificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductoruser',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='conductoruser',
            name='city',
            field=models.CharField(blank=True, choices=[('puerto_vallarta', 'Puerto Vallarta'), ('cancun', 'Cancún'), ('cabo_sanlucas', 'Cabo San Lucas')], default=True, max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='conductoruser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprobado/Sin Aprobar'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_subcategoria',
            field=models.CharField(choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable o Vegana'), ('Tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], default='comida_rapida', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='giro_de_negocio',
            field=models.CharField(blank=True, choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable o Vegana'), ('Tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], max_length=150, null=True),
        ),
    ]
