# Generated by Django 5.0.7 on 2025-07-02 22:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0006_remove_conductoruser_ciudad_conductoruser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tipos_de_negocio',
            field=models.CharField(choices=[('gastronomia_bebidas', [('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable o Vegana')]), ('tiendas_de_conveniencia', [('Tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes')]), ('farmacias', [('medicamentos', 'Medicamentos y otros Productos de Farmacia')]), ('flores_y_regalos', [('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')])], default='comida_rapida', max_length=200),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Extra')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio del Extra (MXN)')),
                ('cantidad_disponible', models.PositiveIntegerField(default=1, verbose_name='Cantidad Disponible')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='ventasapp.producto')),
            ],
        ),
    ]
