# Generated by Django 5.0.7 on 2025-07-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0007_alter_business_tipos_de_negocio_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID de tu cuenta stripe Stripe', max_length=255, null=True),
        ),
    ]
