# Generated by Django 5.0.7 on 2025-07-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0009_cart_cartitem_direcciondeenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='usuario',
        ),
    ]
