# Generated by Django 5.0.7 on 2025-07-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0012_alter_venta_options_pedido_venta_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
