# Generated by Django 5.0.7 on 2025-07-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0013_pedido_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='descripcion',
        ),
    ]
