# Generated by Django 5.0.7 on 2025-07-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0014_remove_extra_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='cantidad_disponible',
        ),
    ]
