# Generated by Django 5.0.7 on 2025-07-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0015_remove_extra_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='extras',
        ),
        migrations.CreateModel(
            name='ExtraEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_en_carrito', to='ventasapp.cartitem')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasapp.extra')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraEnVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasapp.extra')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_en_venta', to='ventasapp.venta')),
            ],
        ),
    ]
