# Generated by Django 5.0.7 on 2025-07-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0016_remove_cartitem_extras_remove_venta_extras_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcciondeenvio',
            old_name='costo_envio',
            new_name='propina',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_de_envio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
