# Generated by Django 5.0.7 on 2025-07-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0017_rename_costo_envio_direcciondeenvio_propina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciondeenvio',
            name='decidir_propina_despues',
            field=models.BooleanField(default=False, verbose_name='Decidir propina después'),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Propina (opcional', max_length=20, null=True),
        ),
    ]
