# Generated by Django 5.0.7 on 2025-07-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0018_direcciondeenvio_decidir_propina_despues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='propina',
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='propina_voluntaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
