# Generated by Django 5.0.7 on 2025-07-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0021_alter_producto_precio_de_envio_alter_producto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
