# Generated by Django 5.0.7 on 2025-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0022_cartitem_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
