# Generated by Django 5.0.7 on 2025-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0023_venta_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Lista de Pedidos', 'verbose_name_plural': 'Lista de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Producto Vendido por separado', 'verbose_name_plural': 'Productos Vendidos por separado'},
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='notas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='propina_voluntaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Propina'),
        ),
    ]
