# Generated by Django 5.0.7 on 2025-07-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0024_alter_pedido_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='commissions',
        ),
        migrations.AlterField(
            model_name='business',
            name='time_category',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno'), ('24_horas', '24 Horas')], default='diurno', max_length=20),
        ),
    ]
