# Generated by Django 5.0.7 on 2025-07-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0025_remove_business_commissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
