# Generated by Django 5.1.4 on 2025-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0029_alter_business_tipos_de_negocio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
