"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-02yns3alesh4gfp)*&b*+m0p+d2@3dyjxz-6#s)w@8_-c%o^)b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ventasapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # ESTO HACE QUE EL SISTEMA SE ADAPTE AL LENGUAJE DEL NAVEGADOR DEL USUARIO
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/


#DJANGO INTENTARA USAR EL IDIOMA DEL MNAVEGADOR, CON EL LocaleMiddleware Y SI NO LO LOGRA USARA EL QUE DERERMINAMOS EN LENGUAGE_CODE
LANGUAGE_CODE = 'en-us'#define el idioma predeterminado del sistema, usado cuando no se puede determinar otro.
TIME_ZONE = 'UTC'
USE_I18N = True #ESTE HACE QUE SE TRADUZCA EL IDIOMA DEL SISTEMA ACORDE A LALOCALIZACION DEL SISTEMA (textos)
USE_L10N = True #ESTE ES EL QUE DETECTA LA LOCACION DEL USUARIO Y CAMBIA EL FORMATO DE LAS FECHAS AUTOMATICAMENTE (fechas)
USE_TZ = True #ESTO ES PARA LO DE LAS ZONAS HORARIAS y si en la app posteamos una hora la convierte a la hora que corresponde en el pais que lo estan viendo (horarios)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import logging
logger = logging.getLogger('django.mail')
logger.setLevel(logging.DEBUG)

# CONFIGURACION PARA ENVIAR EMAILS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'proyectodigitalmexico@gmail.com'
EMAIL_HOST_PASSWORD = 'fjda ypvm egqk gele'
DEFAULT_FROM_EMAIL = 'proyectodigitalmexico@gmail.com'
# Email configuration
DEFAULT_FROM_EMAIL = 'proyectodigitalmexico@gmail.com'
APPOINTMENT_EMAIL = 'proyectodigitalmexico@gmail.com'

"""
STRIPE_PUBLISHABLE_KEY = "pk_live_51PMxD3D4NKq6bhdMHoRJQHTCfgUgB6mo57vhwwleGocI8pHxpngJo7880NPmc7ExG78gdo4TGR9zIldug85fsIWt00EMqY7mcX"
STRIPE_SECRET_KEY = "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"
""" 

STRIPE_PUBLISHABLE_KEY = "pk_test_51PMxD3D4NKq6bhdMwnGjQqKZ1MvYgoSTCAgmB6F3VBkTa3wlaFajTCxZ55FETSXB2DmFYWFX0VDRtB8nRToIVnz300rHytQdUq"
STRIPE_SECRET_KEY = "sk_test_51PMxD3D4NKq6bhdMxg4Kwd9MuRVZcddXpkO1GiKEwkFPHXk7NyzXdQQGnaJWzO8RpNuuyQuqC6MMnschbJcKIl7600oGwUW0Z0"
STRIPE_ACCOUNT_ID = "acct_1PMxD3D4NKq6bhdM"
STRIPE_PRICE_FIRST_BUSINESS = "price_1Rjv61D4NKq6bhdMaZqzioLo" #este es el de 519
STRIPE_PRICE_ADDITIONAL_BUSINESS = "price_1Rjv7lD4NKq6bhdMjiT7G0vJ" #este es el de 419
STRIPE_WEBHOOK_SECRET = "whsec_Wbpoc6l6IRZhgS2aDIkAWg2c1Thva6SD"



